# Generated by Django 2.2 on 2019-07-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(max_length=50, verbose_name='文件类型')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('uid', models.CharField(max_length=50, verbose_name='用户ID')),
                ('realbytes', models.CharField(max_length=50, verbose_name='已用容量')),
                ('softbytes', models.CharField(max_length=50, verbose_name='软阈值')),
                ('hardbytes', models.CharField(max_length=50, verbose_name='硬阈值')),
                ('realinodes', models.CharField(max_length=50, verbose_name='已用文件数')),
                ('softinodes', models.CharField(max_length=50, verbose_name='文件数软阈值')),
                ('hardinodes', models.CharField(max_length=50, verbose_name='文件数硬阈值')),
                ('grace', models.CharField(max_length=50, verbose_name='天数')),
                ('collect_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '用户限额',
                'db_table': 'Quota',
            },
        ),
    ]
