# Generated by Django 2.2 on 2019-08-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cluster_memory_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=50, verbose_name='内存利用率')),
                ('collect_time', models.CharField(default='', max_length=50, verbose_name='收集时间')),
            ],
            options={
                'verbose_name_plural': '内存利用率',
                'db_table': 'cluster_memory_history',
            },
        ),
        migrations.CreateModel(
            name='cluster_cpu_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=50, verbose_name='CPU利用率')),
                ('collect_time', models.CharField(default='', max_length=50, verbose_name='收集时间')),
            ],
            options={
                'verbose_name_plural': 'CPU利用率',
                'db_table': 'cluster_cpu_history',
            },
        ),

        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('uid', models.CharField(max_length=50, verbose_name='用户ID')),
                ('realbytes', models.CharField(max_length=50, verbose_name='已用容量')),
                ('softbytes', models.CharField(max_length=50, verbose_name='软阈值')),
                ('hardbytes', models.CharField(max_length=50, verbose_name='硬阈值')),
                ('realinodes', models.CharField(max_length=50, verbose_name='已用文件数')),
                ('softinodes', models.CharField(max_length=50, verbose_name='文件数软阈值')),
                ('hardinodes', models.CharField(max_length=50, verbose_name='文件数硬阈值')),
                ('grace', models.CharField(max_length=50, verbose_name='天数')),
                ('collect_time', models.CharField(max_length=50, verbose_name='时间戳')),
            ],
            options={
                'verbose_name_plural': '用户限额',
                'db_table': 'Quota',
            },
        ),
        migrations.CreateModel(
            name='Quota_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('uid', models.CharField(default='', max_length=50, verbose_name='用户ID')),
                ('realbytes', models.CharField(default='', max_length=50, verbose_name='已用容量')),
                ('softbytes', models.CharField(default='', max_length=50, verbose_name='软阈值')),
                ('hardbytes', models.CharField(default='', max_length=50, verbose_name='硬阈值')),
                ('realinodes', models.CharField(default='', max_length=50, verbose_name='已用文件数')),
                ('softinodes', models.CharField(default='', max_length=50, verbose_name='文件数软阈值')),
                ('hardinodes', models.CharField(default='', max_length=50, verbose_name='文件数硬阈值')),
                ('grace', models.CharField(default='', max_length=50, verbose_name='天数')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'Quota_user',
            },
        ),
    ]
