# Generated by Django 2.2 on 2019-08-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='qtype',
        ),
    ]
