# Generated by Django 2.2 on 2019-08-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cluster_memory_history',
            table='Cluster_memory_history',
        ),
    ]
