# Generated by Django 2.2 on 2019-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_remove_quota_qtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='collect_time',
            field=models.CharField(max_length=50, verbose_name='时间戳'),
        ),
    ]
