# Generated by Django 2.2 on 2019-08-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190813_0947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cluster_memory_history',
            table='cluster_memory_history',
        ),
    ]
