# Generated by Django 2.2 on 2019-08-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190813_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='queue_alloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=50, verbose_name='队列名称')),
                ('value', models.CharField(max_length=50, verbose_name='占用节点数')),
                ('collect_time', models.CharField(max_length=50, verbose_name='收集时间')),
            ],
            options={
                'verbose_name_plural': '队列占用节点数',
                'db_table': 'queue_alloc',
            },
        ),
    ]
