# Generated by Django 2.2 on 2019-08-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190804_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('softbytes', models.CharField(max_length=50, verbose_name='软阈值')),
                ('hardbytes', models.CharField(max_length=50, verbose_name='硬阈值')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'Quota_user',
            },
        ),
    ]
