# Generated by Django 2.2 on 2019-08-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_quota_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota_user',
            name='grace',
            field=models.CharField(default='', max_length=50, verbose_name='天数'),
        ),
        migrations.AddField(
            model_name='quota_user',
            name='hardinodes',
            field=models.CharField(default='', max_length=50, verbose_name='文件数硬阈值'),
        ),
        migrations.AddField(
            model_name='quota_user',
            name='realbytes',
            field=models.CharField(default='', max_length=50, verbose_name='已用容量'),
        ),
        migrations.AddField(
            model_name='quota_user',
            name='realinodes',
            field=models.CharField(default='', max_length=50, verbose_name='已用文件数'),
        ),
        migrations.AddField(
            model_name='quota_user',
            name='softinodes',
            field=models.CharField(default='', max_length=50, verbose_name='文件数软阈值'),
        ),
        migrations.AddField(
            model_name='quota_user',
            name='uid',
            field=models.CharField(default='', max_length=50, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='quota_user',
            name='hardbytes',
            field=models.CharField(default='', max_length=50, verbose_name='硬阈值'),
        ),
        migrations.AlterField(
            model_name='quota_user',
            name='softbytes',
            field=models.CharField(default='', max_length=50, verbose_name='软阈值'),
        ),
        migrations.AlterField(
            model_name='quota_user',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
    ]
